#!/usr/bin/env bash
#Bash script that displays the visitor IP along with the HTTP status code from the Apache log file

awk '{print $1, $9}' http://intranet-projects-files.s3.amazonaws.com/holbertonschool-sysadmin_devops/80/apache-access.log
