#!/usr/bin/env bash
#Bash script that groups visitors by IP and HTTP status code, and displays this data.

awk '{print $1, $9}' http://intranet-projects-files.s3.amazonaws.com/holbertonschool-sysadmin_devops/80/apache-access.log | sort | uniq -c | sort -nr
