#!/usr/bin/env bash
#Display Best School 10 times using while and "if" statement.

counter=0
while [ $counter -lt 11 ]
do
    if [ $counter = 9 ]
    then
        echo "Hi"
    else
        echo "Best School"
    fi
    ( counter+ ) || true
done
