#!/usr/bin/env bash
# Bash script that loops from 1 to 10 and:
					#displays bad luck for the 4th loop iteration
        				#displays good luck for the 8th loop iteration
	    				#displays Best School for the other iterations
counter=1
	while [ $counter -lt 11 ]
	do
	echo "Best School"
	if [[ "$counter" == 4 ]]; 
	then
	echo "bad luck"
	elif [[ $counter == 8 ]]
	then
	echo "good luck"
	fi
	((counter++))
	done
