#!/usr/bin/env bash
#Bash script that gives you information about the school file.
file="school"
if [ -s "$file" ] #si es un archivo
	then #entonces
	echo "school file does not exist"
	else 
	echo "school file exists"
	fi
if [ -f "$file" ]
        then 
        echo "school is a regular file"
        else
        echo "school file does not exist"
        fi
