#!/bin/bash
echo 'Everyone is a proponent of strong encryption. Dorothy E. Denning' | tr 'A-Za-z' 'N-ZA-Mn-za-m' | 'Rirelbar vf n cebcbarag bs fgebat rapelcgvba. Qbebgul R. Qraavat' | tr 'A-Za-z' 'N-ZA-Mn-za-m'
