#!/usr/bin/env bash
#create f
pid=$/var/run/myscript.pid

echo $$ >> $pid

while true
	        
do
	echo "To infinity and beyond"
	sleep 2
done
	trap echo "Y U no love me?!" $pid SIGINT
	trap echo "I hate the kill command" $pid SIGTERM
	trap rm $pid SIGQUIT
