#!/usr/bin/env bash
#Manage my process

pid=/var/run/my_process.pid
aaa=manage_my_process

case $1 in
	
        start)
		        ./$aaa &
			        echo $! > $pid
				        echo "manage_my_process started"
					        ;;
						        
        stop)
		        kill -9 $aaa
			        rm -f $pid
				        echo "manage_my_process stopped"
					        ;;
						        
        restart)
		        kill -9 $aaa
			        rm -f $pid
				        ./$aaa &
					        echo $! > $pid
						        echo "manage_my_process restarted"
							        ;;
								
        *)
		        echo "Usage: manage_my_process {start|stop|restart}"
			        ;;
		esac
