#!/usr/bin/env bash
#Manage my process

pid=/var/run/my_process.pid
aaa=manage_my_process

/etc/init.d/$aaa start
echo $$ > $pid
while :
do
	        echo "manage_my_process started"
	done
	
/etc/init.d/$aaa stop
rm $pid
while :
do
	        echo "manage_my_process stopped"
	done
	
/etc/init.d/$aaa stop
rm $pid
/etc/init.d/$aaa start
echo $$ > $pid
while :
do
	        echo "manage_my_process restarted"
	done
	
while :
do
	        echo "Usage: manage_my_process {start|stop|restart}"
	done
