#!/usr/bin/env bash
#Manage my process

pid=/var/run/my_process.pid
aaa=manage_my_process

/etc/init.d/$aaa & $pid start

case $aaa in
	
        start)
		        /etc/init.d/$aaa start
			        echo "$!" > $pid
				        echo "manage_my_process started"
					        ;;
						        
        stop)
		        /etc/init.d/$aaa stop
			        rm $pid
				        echo "manage_my_process stopped"
					        ;;
						        
        restart)
		        /etc/init.d/$aaa stop
			        rm $pid
				        /etc/init.d/$aaa start
					        echo $$ > $pid
						        echo "manage_my_process restarted"
							        ;;
								
        *)
		        echo "Usage: manage_my_process {start|stop|restart}"
			        ;;
		esac
